[package]
name = "md-lsp"
version = "0.1.0"
edition = "2024"

[dependencies]
lsp-types = "0.97"
lsp-server = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
miette = { version = "7.6", features = ["fancy"] }
mq-markdown = "0.5.10"
